settings:
  title: 'Network Status'
  url: 'https://status.morgverd.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Services Downgraded'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: com
    name: 'Main Website'
    description: 'The main website homepage.'
    url: 'https://morgverd.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: cdn
    name: 'Content Delivery Network'
    description: 'Content Delivery Network master server.'
    url: 'https://cdn.morgverd.com'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: uk-01
    name: 'UK-01'
    url: 'https://01.uk.nodes.morgverd.com/'
    method: GET
    expectStatus: 302
    linkable: false
    followRedirect: false

  - id: uk-02
    name: 'UK-02'
    url: 'https://02.uk.nodes.morgverd.com/'
    method: GET
    expectStatus: 302
    linkable: false
    followRedirect: false

  - id: uk-03
    name: 'UK-03'
    url: 'https://03.uk.nodes.morgverd.com/'
    method: GET
    expectStatus: 302
    linkable: false
    followRedirect: false

  - id: uk-04
    name: 'UK-04'
    url: 'https://04.uk.nodes.morgverd.com/'
    method: GET
    expectStatus: 302
    linkable: false
    followRedirect: false
