settings:
  title: 'Network Status'
  url: 'https://status.morgverd.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Services Downgraded'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: morgverd-com
    name: morgverd.com
    description: 'The main website homepage.'
    url: 'https://morgverd.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: cdn
    name: cdn.morgverd.com
    description: 'Content Delivery Network master server.'
    url: 'https://cdn.morgverd.com'
    method: GET
    expectStatus: 200
    linkable: true

  - id: morgverd.dev
    name: morgverd.dev
    description: 'The main development workspace.'
    url: 'https://morgverd.dev/'
    method: GET
    expectStatus: 200
